version: "3"

services:
  database:
    build:
      context: "./dockerfile/mariadb"
    container_name: 'mariadb'
    restart: 'always'
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
  phpapp:
    build:
     context: "."
    depends_on:
      - database
      - redis
    container_name: 'phpapp'
    links:
      - database
    ports:
      - "8080:8080"
    environment:
     APP_NAME:
     APP_ENV:
     APP_KEY:
     APP_DEBUG:
     APP_LOG_LEVEL:
     APP_URL: 
     DB_CONNECTION:
     DB_HOST:
     DB_PORT:
     DB_DATABASE:
     DB_USERNAME:
     DB_PASSWORD:
     BROADCAST_DRIVER:
     CACHE_DRIVER:
     SESSION_DRIVER:
     SESSION_LIFETIME:
     QUEUE_DRIVER:
     REDIS_HOST:
     REDIS_PASSWORD:
     REDIS_PORT:
     MAIL_DRIVER:
     MAIL_HOST:
     MAIL_PORT:
     MAIL_USERNAME:
     MAIL_PASSWORD:
     MAIL_ENCRYPTION:
     PUSHER_APP_ID:
     PUSHER_APP_KEY:
     PUSHER_APP_SECRET:
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
